services:
  docs:
    image: mdeck_local_docs
    container_name: mdeck_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./mdeck:/app/mdeck:z
    ports:
      - '9000:9000'
    command: /start-docs
